### ISSUE TITLE
Some problem about https://github.com/sdss/lvmsurveysim/blob/master/lvmsurveysim/utils/shadow_height_lib.py

### ISSUE THREAD

**Issue by AlanJeager** [sdss/lvmscheduler#2]
I have encountered some problems as I run this file(shadow_height_lib.py), those problems are about "orbit animation"  is the,let me make a list.
First, in the line 298.  the function called"position_from_radec" was a undefined name.and I don't know how to define this function. 
Second, in the line 344:import lvmsurveysim.utils.iterative_shadow_height_lib as iterative_shadow_height_lib
there's no file caalled  "iterative_shadow_height_lib", I thought you may wanted to reload the shadow_height_lib ,  so I delete the "iterative".  in the line:349:"iter_calc.update_t(jd)" . I thoiught you made a  small mistake here, this should be "iter_calc.update_time(jd), you may missed 'ime' here.
This is all the problems I've encountered. Maybe my English isn't so well, I' m so sorry that I bring a lot of trouble for you. If you are available, I'm really looking forward to get  your  help.

**Comment by johndonor3** [comment]
Both of these issues appear to be with deprecated code. I'm not sure why you're trying to use code that's literally commented out?
